# Loan Default Risk Dashboard
# Consumes the LOAN_PREDICTIONS view created by the orbital workflow.
#
# BEFORE YOUR FIRST RUN:
#   Run scripts/setup-demo-data.sql to create sample data.
#
# CONFIGURE via environment variables (or edit defaults below):
#   DEMO_DATABASE  — default: SOL_ENG_DEMO
#   DEMO_SCHEMA    — default: COCO_DEMO
#
# Deploy with:
#   rsconnect::deployApp(appDir = ".", appName = "loan-dashboard")
#
# Cleanup after demo:
#   Run scripts/teardown-demo.sql

library(shiny)
library(bslib)
library(DBI)
library(dplyr)
library(ggplot2)
library(scales)

# ── Configuration ─────────────────────────────────────────────────────────────
DEMO_DB     <- Sys.getenv("DEMO_DATABASE", "SOL_ENG_DEMO")
DEMO_SCHEMA <- Sys.getenv("DEMO_SCHEMA", "COCO_DEMO")
FQN         <- paste(DEMO_DB, DEMO_SCHEMA, sep = ".")

# ── UI ────────────────────────────────────────────────────────────────────────

ui <- page_sidebar(
 title = "Loan Default Risk",
 theme = bs_theme(preset = "flatly", primary = "#447099"),

 sidebar = sidebar(
   title = "Filters",
   sliderInput(
     "risk_threshold", "Default probability threshold",
     min = 0, max = 1, value = 0.5, step = 0.05
   ),
   selectInput(
     "term_filter", "Loan term",
     choices = c("All", "36 months", "60 months"),
     selected = "All"
   ),
   hr(),
   p(class = "text-muted small",
     "Predictions generated by tidymodels + orbital.",
     "Scoring runs as native Snowflake SQL — no R runtime required.",
     "Each viewer sees only loans permitted by their Snowflake role.")
 ),

 layout_columns(
   col_widths = c(4, 4, 4),

   value_box(
     title    = "Total applications",
     value    = textOutput("total_count"),
     showcase = bsicons::bs_icon("file-earmark-text")
   ),
   value_box(
     title    = "Flagged high risk",
     value    = textOutput("high_risk_count"),
     theme    = "danger",
     showcase = bsicons::bs_icon("exclamation-triangle")
   ),
   value_box(
     title    = "Avg default probability",
     value    = textOutput("avg_prob"),
     showcase = bsicons::bs_icon("graph-up")
   )
 ),

 layout_columns(
   col_widths = c(6, 6),
   card(
     card_header("Default probability distribution"),
     plotOutput("prob_histogram")
   ),
   card(
     card_header("Risk by credit score band"),
     plotOutput("risk_by_credit")
   )
 ),

 card(
   card_header("High-risk applications"),
   DT::dataTableOutput("risk_table")
 )
)

# ── Server ────────────────────────────────────────────────────────────────────

server <- function(input, output, session) {

 # Connection — in Native App, inherits viewer OAuth token automatically
 con <- DBI::dbConnect(odbc::odbc(), dsn = "snowflake")
 onStop(function() DBI::dbDisconnect(con))

 # Remote reference to the orbital-generated predictions view
 predictions_tbl <- tbl(con, in_schema(FQN, "LOAN_PREDICTIONS"))

 # Filtered data (reactive, runs SQL in Snowflake)
 filtered_data <- reactive({
   q <- predictions_tbl

   if (input$term_filter != "All") {
     q <- q |> filter(term == !!input$term_filter)
   }

   q |> collect()
 })

 # ── Value boxes ──
 output$total_count <- renderText({
   comma(nrow(filtered_data()))
 })

 output$high_risk_count <- renderText({
   filtered_data() |>
     filter(.pred_default >= input$risk_threshold) |>
     nrow() |>
     comma()
 })

 output$avg_prob <- renderText({
   filtered_data() |>
     summarise(avg = mean(.pred_default, na.rm = TRUE)) |>
     pull(avg) |>
     percent(accuracy = 0.1)
 })

 # ── Plots ──
 output$prob_histogram <- renderPlot({
   filtered_data() |>
     ggplot(aes(x = .pred_default)) +
     geom_histogram(
       binwidth = 0.05,
       fill     = "#447099",
       color    = "white"
     ) +
     geom_vline(
       xintercept = input$risk_threshold,
       linetype   = "dashed",
       color      = "#D9534F",
       linewidth  = 1
     ) +
     annotate(
       "text",
       x     = input$risk_threshold + 0.03,
       y     = Inf,
       label = "Threshold",
       vjust = 2,
       color = "#D9534F",
       fontface = "bold"
     ) +
     scale_x_continuous(labels = percent_format()) +
     labs(x = "Predicted default probability", y = "Count") +
     theme_minimal(base_size = 13)
 })

 output$risk_by_credit <- renderPlot({
   filtered_data() |>
     mutate(credit_band = cut(
       credit_score,
       breaks = c(0, 580, 670, 740, 800, Inf),
       labels = c("Poor", "Fair", "Good", "Very Good", "Excellent")
     )) |>
     group_by(credit_band) |>
     summarise(
       avg_risk = mean(.pred_default, na.rm = TRUE),
       n        = n(),
       .groups  = "drop"
     ) |>
     ggplot(aes(x = credit_band, y = avg_risk, fill = avg_risk)) +
     geom_col() +
     geom_text(aes(label = comma(n)), vjust = -0.5, size = 3.5) +
     scale_y_continuous(labels = percent_format()) +
     scale_fill_gradient(low = "#447099", high = "#D9534F", guide = "none") +
     labs(
       x = "Credit score band",
       y = "Average default probability",
       caption = "Numbers above bars = application count"
     ) +
     theme_minimal(base_size = 13)
 })

 # ── Table ──
 output$risk_table <- DT::renderDataTable({
   filtered_data() |>
     filter(.pred_default >= input$risk_threshold) |>
     select(
       loan_amount,
       credit_score,
       annual_income,
       term,
       default_probability = .pred_default
     ) |>
     arrange(desc(default_probability)) |>
     DT::datatable(
       options  = list(pageLength = 10, scrollX = TRUE),
       rownames = FALSE
     ) |>
     DT::formatPercent("default_probability", digits = 1) |>
     DT::formatCurrency("loan_amount", digits = 0) |>
     DT::formatCurrency("annual_income", digits = 0)
 })
}

shinyApp(ui, server)
